### ISSUE TITLE
Button

### ISSUE THREAD

**Issue by KhairUnNisa10** [Kainatn/May-14-task#2]
https://github.com/Kainatn/May-14-task/blob/e49d8d5b814206c87672f4186589fa7d4a64afc9/style.css#L114-L122

Do not use height/width to increase the size of the button. Use padding for the sizing of the button.

**Comment by KhairUnNisa10** [comment]
https://github.com/Kainatn/May-14-task/blob/49726c2bcc555ee6c564674538dcd8cbf6dad210/style.css#L111  

you have write like this: padding: 1em 2em 1em 2em; (shorthand way for padding: padding: top/left/bottom/right) But in this case you have written top/bottom same i.e 1em and left/right same i.e. 2em but the repetition is used. Instead a shorthand way for padding is like this padding: top/bottom left/right... padding: 1em (for top/bottom) 2em(for left/right).

**Comment by KhairUnNisa10** [comment]
Still not solved.

**Comment by Kainatn** [comment]
Ohh yh to dekha hi ni mne
