### ISSUE TITLE
Paragraphs

### ISSUE THREAD

**Issue by KhairUnNisa10** [Kainatn/May-14-task#3]
https://github.com/Kainatn/May-14-task/blob/49726c2bcc555ee6c564674538dcd8cbf6dad210/index.html#L41-L43

No closing tag of p. Also break the paragraph into two lines like in the mock-up. 
The border length should be as same as the length of the paragraph. 

https://github.com/Kainatn/May-14-task/blob/49726c2bcc555ee6c564674538dcd8cbf6dad210/index.html#L105-L107
The border length should be as same as the length of the paragraph.

**Comment by KhairUnNisa10** [comment]
Still not solved.

**Comment by Kainatn** [comment]
Miss yh to solved he?

**Comment by KhairUnNisa10** [comment]
Yes its done now.
